project:
  type: onlimit-theme

format:
  onlimit-theme-html:
    theme:
      - brand

website:
  page-navigation: true
  title: "ON-LiMiT Docs"
  site-url: "https://onlimit-study.github.io/data-documentation/"
  repo-url: "https://github.com/onlimit-study/data-documentation"
  navbar:
    left:
      - text: "Data Design"
        menu:
          - href: documents/C4-level.qmd
          - href: documents/data-flow.qmd
editor:
  markdown:
    wrap: 72
    canonical: true
