name: Auto-assign PR creator

on:
  pull_request:
    types:
      - reopened
      - opened

jobs:
  auto-assign:
    name: Auto-assign PR creator
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Assign PR to creator
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          gh pr edit $PR --add-assignee $AUTHOR --repo $REPO
        env:
          REPO: ${{ github.repository }}
          AUTHOR: ${{ github.event.pull_request.user.login }}
          PR: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
