name: Build website

on:
  push:
    branches:
      - main

# Limit permissions to minimal needed.
permissions: read-all

jobs:
  build-deploy-docs:
    uses: seedcase-project/.github/.github/workflows/reusable-build-docs.yml@main
    permissions:
      contents: write
      pages: write
    with:
      hosting-provider: 'gh-pages'
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
